version: "3"
services:
  app:
    build:
      context: ./djangomysql
      dockerfile: Dockerfile
    entrypoint: ["./wait.sh"]
    links:
      - db
    ports:
      - "8000:8000"

  apache2:
    image: webdevops/apache:latest
    volumes:
      - ../www:/var/www/html
    ports:
      - 80:80
      - 443:443
    links:
      - db

  db:
    image: mysql:8.0.21
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8082:8082
    volumes:
      - /sessions
